<x-layouts.app>
@php($images = config('chateau.images'))
<header class="site-header" data-header>
 <div class="container nav-wrap"><a href="#inicio" class="brand" aria-label="Chateau Catedral, inicio"><x-logo /></a>
 <button class="menu-toggle" type="button" aria-expanded="false" aria-controls="main-nav"><span></span><span></span><span></span><span class="sr-only">Abrir menú</span></button>
 <nav id="main-nav" aria-label="Navegación principal"><a href="#cabana">La cabaña</a><a href="#comodidades">Comodidades</a><a href="#galeria">Galería</a><a href="#ubicacion">Ubicación</a><x-whatsapp-link class="button button-small">Consultar disponibilidad</x-whatsapp-link></nav></div>
</header>
<main id="contenido">
 <section class="hero" id="inicio">
  <div class="hero-media"><video autoplay muted loop playsinline preload="metadata" poster="{{ asset('assets/images/WhatsApp Image 2026-09-09 at 16.33.35.jpeg') }}" aria-label="Chateau Catedral y su entorno de montaña"><source src="{{ asset('assets/images/WhatsApp Video 2026-09-09 at 16.34.09.mp4') }}" type="video/mp4"></video></div>
  <div class="hero-shade"></div><div class="container hero-copy"><p class="eyebrow">Villa Catedral · Bariloche</p><h1>Tu refugio al pie del Cerro Catedral</h1><p>Una cabaña de montaña para hasta 7 personas, a 200 metros de las pistas.</p><div class="actions"><x-whatsapp-link>Consultar disponibilidad</x-whatsapp-link><a class="text-link light" href="#cabana">Conocé la cabaña <span aria-hidden="true">↓</span></a></div></div>
 </section>
 <section class="facts" aria-label="Datos destacados"><div class="container facts-grid">
  @foreach([['people','Hasta','7 huéspedes'],['home','150 m²','cubiertos'],['bed','3 dormitorios','en suite'],['mountain','A 200 m','de las pistas']] as $fact)
   <div class="fact"><x-icon :name="$fact[0]"/><p><strong>{{ $fact[1] }}</strong><span>{{ $fact[2] }}</span></p></div>
  @endforeach
 </div></section>
 <section class="section intro" id="cabana"><div class="container split"><div class="section-copy"><p class="eyebrow dark">La cabaña</p><h2>La calidez de la montaña, en cada rincón</h2><p>Ubicada en la base del Cerro Catedral, Chateau Catedral combina la calidez de la madera y la piedra con espacios pensados para descansar y compartir. A solo 200 metros de las pistas, ofrece 150 m² cubiertos y capacidad para hasta 7 personas.</p><p>Tres dormitorios en suite brindan privacidad durante la estadía, mientras que el living con chimenea y el quincho propio invitan a disfrutar de la cabaña después de un día en la montaña.</p></div><x-image file="WhatsApp Image 2026-09-09 at 16.32.19.jpeg" alt="Living cálido de madera de Chateau Catedral" class="feature-image" /></div></section>
 <section class="section rest"><div class="container split reverse"><x-image file="WhatsApp Image 2026-09-09 at 16.33.06.jpeg" alt="Detalles artesanales en madera y acceso a uno de los baños" class="feature-image bedroom" /><div class="section-copy"><p class="eyebrow dark">Dormitorios y descanso</p><h2>Descansar también es parte del viaje</h2><ul class="check-list"><li>Tres dormitorios, cada uno con baño propio.</li><li>Jacuzzi en la suite principal.</li><li>Posibilidad de armar hasta tres camas matrimoniales.</li><li>Practicuna con sábanas para bebé.</li><li>Cambio de blancos.</li></ul></div></div></section>
 <section class="section amenities" id="comodidades"><div class="container"><div class="section-heading"><p class="eyebrow dark">Todo lo necesario</p><h2>Comodidades para sentirte en casa</h2></div><div class="amenity-grid">
 @foreach([['utensils','Para compartir',['Quincho propio cubierto con parrilla.','Cocina completa.','Barra con cava de vinos.']],['flame','Confort',['Chimenea.','Calefacción por piso radiante.','Caldera para calefacción.','Termotanque de alta recuperación para agua caliente.']],['wifi','Conectividad',['Wi-Fi.','TV de pantalla plana de 50 pulgadas con DirecTV.']],['shield','Servicios y seguridad',['Servicio de limpieza lunes, miércoles y viernes, solo durante el invierno.','Cambio de blancos.','Alarma e iluminación perimetral.']]] as $group)
 <article class="amenity"><x-icon :name="$group[0]"/><h3>{{ $group[1] }}</h3><ul>@foreach($group[2] as $item)<li>{{ $item }}</li>@endforeach</ul></article>
 @endforeach</div></div></section>
 <section class="section gallery" id="galeria"><div class="container"><div class="section-heading"><p class="eyebrow dark">Galería</p><h2>Una cabaña hecha para la montaña</h2></div><div class="gallery-grid">
 @foreach($images as $index => $photo)<button type="button" class="gallery-item item-{{ $index + 1 }}" data-gallery-index="{{ $index }}" aria-label="Ampliar: {{ $photo['alt'] }}"><x-image :file="$photo['file']" :alt="$photo['alt']" /></button>@endforeach
 </div></div></section>
 <section class="section location" id="ubicacion"><div class="container location-grid"><div><p class="eyebrow">Ubicación</p><h2>La montaña, a pocos pasos</h2><p>Estamos en Villa Catedral, en la base del Cerro Catedral, Bariloche, a 200 metros de las pistas.</p><a class="text-link light" href="https://www.google.com/maps/search/?api=1&query=Cerro+Catedral%2C+Bariloche" target="_blank" rel="noopener noreferrer">Ver la zona de Cerro Catedral <span aria-hidden="true">↗</span></a><small>El mapa muestra la zona; la ubicación exacta se informará al reservar.</small></div><div class="map-placeholder" aria-hidden="true"><x-icon name="mountain"/><span>Villa Catedral</span><i></i><span>Bariloche</span></div></div></section>
 <section class="section contact" id="contacto"><div class="container contact-inner"><p class="eyebrow dark">Consultas y reservas</p><h2>Planeá tu próxima escapada</h2><p class="lead">Consultanos por disponibilidad y tarifas para las fechas de tu viaje.</p><p class="booking-note">Para confirmar la reserva solicitamos una seña del 50 %. El saldo se abona al ingresar a la cabaña.</p><div class="contact-person"><strong>{{ config('chateau.contact.name') }}</strong><a href="tel:+5491151205507">{{ config('chateau.contact.phone') }}</a></div><x-whatsapp-link>Consultar por WhatsApp</x-whatsapp-link></div></section>
</main>
<footer><div class="container footer-grid"><div><x-logo/><p>{{ config('chateau.location') }}</p></div><nav aria-label="Navegación del pie"><a href="#cabana">La cabaña</a><a href="#comodidades">Comodidades</a><a href="#galeria">Galería</a><a href="#ubicacion">Ubicación</a></nav><div><p><strong>{{ config('chateau.contact.name') }}</strong></p><a href="tel:+5491151205507">{{ config('chateau.contact.phone') }}</a></div></div><div class="container copyright">© <span data-year>{{ date('Y') }}</span> Chateau Catedral</div></footer>
<x-whatsapp-link class="whatsapp-float" aria-label="Consultar disponibilidad por WhatsApp"><span class="sr-only">WhatsApp</span></x-whatsapp-link>
<div class="lightbox" data-lightbox hidden aria-hidden="true"><div class="lightbox-backdrop" data-close></div><div class="lightbox-dialog" role="dialog" aria-modal="true" aria-label="Visor de fotografías"><button class="lightbox-close" type="button" data-close aria-label="Cerrar visor">×</button><button class="lightbox-arrow prev" type="button" data-prev aria-label="Fotografía anterior">←</button><div data-lightbox-image></div><p data-lightbox-caption></p><button class="lightbox-arrow next" type="button" data-next aria-label="Fotografía siguiente">→</button></div></div>
<script type="application/json" id="gallery-data">{!! json_encode($images, JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE) !!}</script>
</x-layouts.app>
