<?php

return [
    'meta' => ['title' => 'Chateau Catedral | Cabins and apartment in Villa Catedral', 'description' => 'Two cabins and an apartment in Villa Catedral, just metres from the ski slopes. Enquire about availability.', 'short_description' => 'Two cabins and an apartment in Villa Catedral, close to the slopes.'],
    'a11y' => ['skip' => 'Skip to content', 'menu' => 'Open menu', 'navigation' => 'Main navigation', 'footer_navigation' => 'Footer navigation', 'language' => 'Select language'],
    'hero' => ['discover' => 'Discover'],
    'nav' => ['cabins' => 'The cabins', 'apartment' => 'Apartment', 'amenities' => 'Amenities', 'gallery' => 'Gallery', 'location' => 'Locations', 'book' => 'Book'],
    'cabins' => ['title' => 'The cabins', 'p1' => 'At the foot of Cerro Catedral, Chateau Catedral combines the warmth of timber and stone with spaces designed for relaxing and sharing.', 'p2' => 'Only 200 metres from the slopes, each cabin offers 150 m² of indoor space for up to 7 guests. Three en-suite bedrooms provide privacy, while the fireplace lounge and private barbecue room are perfect after a day in the mountains.'],
    'amenities' => ['eyebrow' => 'Everything included in your stay', 'title' => 'Amenities', 'cabins' => 'First, the cabins', 'apartment' => 'Then, the apartment', 'items' => [
        ['title' => 'Time together', 'text' => 'Private covered barbecue room with grill, full kitchen, bar and wine cellar.'],
        ['title' => 'Comfort', 'text' => 'Fireplace, underfloor heating and high-recovery hot water.'],
        ['title' => 'Rest', 'text' => 'Three en-suite bedrooms, a hot tub in the main suite and a travel cot.'],
        ['title' => 'Services', 'text' => 'Wi-Fi, DirecTV, linen changes, alarm and perimeter lighting.'],
    ]],
    'apartment' => ['eyebrow' => 'Latitud Catedral · 300 metres from the slopes', 'title' => 'The apartment', 'intro' => 'A warm, fully equipped two-bedroom apartment for 6 guests, with room for 2 additional beds in the lounge.', 'image_alt' => 'Living room, dining room and kitchen in the Latitud Catedral apartment', 'inside_title' => 'Inside the apartment', 'inside' => ['Living room, dining area and full kitchen.', 'Very spacious main bedroom.', 'Second bedroom with four beds.', 'Sleeps 6, with the option of adding 2 beds in the lounge.', '2 full bathrooms and 1 guest toilet.', 'Bed linen and towels included.', 'Safe, 50-inch Smart TV, Wi-Fi and underfloor heating.', 'Housekeeping in winter on Mondays, Wednesdays and Fridays, including one towel change (no sheet change).'], 'building_title' => 'The building offers', 'building' => ['Lift.', 'Heated indoor/outdoor pool.', 'Hot tub and sauna.', 'Indoor children’s play area.', 'Parking.']],
    'gallery' => ['cabins' => 'The cabins', 'apartment' => 'The apartment', 'eyebrow' => 'Gallery', 'title' => 'Two ways to experience the mountain', 'intro' => 'Explore each property separately and open any image for a closer look.', 'open' => 'Enlarge photograph', 'viewer' => 'Photo viewer', 'close' => 'Close viewer', 'previous' => 'Previous photograph', 'next' => 'Next photograph'],
    'dividers' => ['winter' => 'Chateau Catedral among snow-covered pines', 'apartment' => 'Snowy view from the apartment', 'fire' => 'The glowing fireplace', 'location' => 'Chateau Catedral in the forest during summer'],
    'location' => ['eyebrow' => 'Villa Catedral · Bariloche', 'title' => 'Locations', 'intro' => 'The cabins and apartment are both in Villa Catedral, close to the slopes. Choose a property to view its map or start directions.', 'directions_button' => 'Get directions',
        'cabins' => ['type' => 'The cabins', 'name' => 'Chateau Catedral', 'address' => 'Martín Jereb 9857, Villa Catedral', 'directions' => '200 metres from the slopes. From central Bariloche, take Avenida Bustillo and then the Cerro Catedral access road.', 'map_title' => 'Interactive map of the Chateau Catedral cabins'],
        'apartment' => ['type' => 'The apartment', 'name' => 'Latitud Catedral', 'address' => 'Villa Catedral, San Carlos de Bariloche', 'directions' => '300 metres from the slopes in Villa Catedral. Open directions for a precise route from your current location.', 'map_title' => 'Interactive map of the Latitud Catedral apartment'],
    ],
    'contact' => ['kicker' => 'Enquiries and bookings', 'title' => 'Your next getaway<br>starts here', 'text' => 'Ask us about availability and rates for your travel dates.', 'note' => 'A 50% deposit is required to confirm your booking. The balance is payable upon arrival. Bookings are non-refundable.', 'whatsapp' => 'Enquire on WhatsApp'],
];
