<?php

return [
    'meta' => ['title' => 'Chateau Catedral | Cabanas e apartamento em Villa Catedral', 'description' => 'Duas cabanas e um apartamento em Villa Catedral, a poucos metros das pistas de esqui. Consulte a disponibilidade.', 'short_description' => 'Duas cabanas e um apartamento em Villa Catedral, perto das pistas.'],
    'a11y' => ['skip' => 'Pular para o conteúdo', 'menu' => 'Abrir menu', 'navigation' => 'Navegação principal', 'footer_navigation' => 'Navegação do rodapé', 'language' => 'Selecionar idioma'],
    'hero' => ['discover' => 'Descobrir'],
    'nav' => ['cabins' => 'As cabanas', 'apartment' => 'Apartamento', 'amenities' => 'Comodidades', 'gallery' => 'Galeria', 'location' => 'Localizações', 'book' => 'Reservar'],
    'cabins' => ['title' => 'As cabanas', 'p1' => 'Localizadas na base do Cerro Catedral, o Chateau Catedral combina o aconchego da madeira e da pedra com espaços pensados para descansar e compartilhar.', 'p2' => 'A apenas 200 metros das pistas, cada cabana oferece 150 m² cobertos e capacidade para até 7 pessoas. Três suítes garantem privacidade, enquanto a sala com lareira e o espaço gourmet privativo convidam a relaxar depois de um dia na montanha.'],
    'amenities' => ['eyebrow' => 'Tudo o que sua estadia inclui', 'title' => 'Comodidades', 'cabins' => 'Primeiro, as cabanas', 'apartment' => 'Depois, o apartamento', 'items' => [
        ['title' => 'Para compartilhar', 'text' => 'Espaço gourmet coberto e privativo com churrasqueira, cozinha completa, bar e adega.'],
        ['title' => 'Conforto', 'text' => 'Lareira, piso aquecido e água quente de alta recuperação.'],
        ['title' => 'Descanso', 'text' => 'Três suítes, jacuzzi na suíte principal e berço portátil.'],
        ['title' => 'Serviços', 'text' => 'Wi-Fi, DirecTV, troca de roupas de cama, alarme e iluminação perimetral.'],
    ]],
    'apartment' => ['eyebrow' => 'Latitud Catedral · a 300 metros das pistas', 'title' => 'O apartamento', 'intro' => 'Um apartamento acolhedor e totalmente equipado, com dois quartos, capacidade para 6 pessoas e opção de 2 camas extras na sala.', 'image_alt' => 'Sala de estar, jantar e cozinha do apartamento Latitud Catedral', 'inside_title' => 'O apartamento oferece', 'inside' => ['Sala de estar, jantar e cozinha completa.', 'Quarto principal muito espaçoso.', 'Segundo quarto com quatro camas.', 'Capacidade para 6 pessoas e opção de adicionar 2 camas na sala.', '2 banheiros completos e 1 lavabo.', 'Roupa de cama e banho incluída.', 'Cofre, Smart TV de 50 polegadas, Wi-Fi e piso aquecido.', 'Serviço de limpeza no inverno às segundas, quartas e sextas, com uma troca de toalhas (sem troca de lençóis).'], 'building_title' => 'O edifício oferece', 'building' => ['Elevador.', 'Piscina aquecida interna e externa.', 'Jacuzzi e sauna.', 'Espaço de jogos interno para crianças.', 'Estacionamento.']],
    'gallery' => ['cabins' => 'As cabanas', 'apartment' => 'O apartamento', 'eyebrow' => 'Galeria', 'title' => 'Duas formas de viver a montanha', 'intro' => 'Explore cada hospedagem separadamente e abra qualquer imagem para vê-la em detalhes.', 'open' => 'Ampliar fotografia', 'viewer' => 'Visualizador de fotos', 'close' => 'Fechar visualizador', 'previous' => 'Fotografia anterior', 'next' => 'Próxima fotografia'],
    'dividers' => ['winter' => 'Chateau Catedral entre pinheiros cobertos de neve', 'apartment' => 'Vista nevada do apartamento', 'fire' => 'O fogo aceso da lareira', 'location' => 'Chateau Catedral na floresta durante o verão'],
    'location' => ['eyebrow' => 'Villa Catedral · Bariloche', 'title' => 'Localizações', 'intro' => 'As cabanas e o apartamento ficam em Villa Catedral, perto das pistas. Escolha uma hospedagem para ver o mapa ou iniciar as direções.', 'directions_button' => 'Como chegar',
        'cabins' => ['type' => 'As cabanas', 'name' => 'Chateau Catedral', 'address' => 'Martín Jereb 9857, Villa Catedral', 'directions' => 'A 200 metros das pistas. Do centro de Bariloche, siga pela Avenida Bustillo e depois pela estrada de acesso ao Cerro Catedral.', 'map_title' => 'Mapa interativo das cabanas Chateau Catedral'],
        'apartment' => ['type' => 'O apartamento', 'name' => 'Latitud Catedral', 'address' => 'Villa Catedral, San Carlos de Bariloche', 'directions' => 'A 300 metros das pistas, em Villa Catedral. Abra as direções para obter a rota exata a partir da sua localização.', 'map_title' => 'Mapa interativo do apartamento Latitud Catedral'],
    ],
    'contact' => ['kicker' => 'Consultas e reservas', 'title' => 'Sua próxima viagem<br>começa aqui', 'text' => 'Consulte disponibilidade e tarifas para as datas da sua viagem.', 'note' => 'Para confirmar a reserva, solicitamos um sinal de 50%. O saldo é pago na chegada. A reserva não é reembolsável.', 'whatsapp' => 'Consultar pelo WhatsApp'],
];
